# Generated by Django 4.2.1 on 2023-06-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ichimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('rasm', models.ImageField(upload_to='ichimlik')),
            ],
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('batafsil', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('fam', models.CharField(max_length=255)),
                ('soha', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='xodim')),
            ],
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('qisqa_matn', models.CharField(max_length=350)),
                ('batafsil', models.TextField()),
                ('rasm', models.ImageField(upload_to='yangilik')),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=15)),
                ('fikr', models.TextField(blank=True, null=True)),
                ('ichimlik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.ichimlik')),
                ('xizmat', models.ManyToManyField(blank=True, to='mainApp.xizmat')),
            ],
        ),
    ]
