# Generated by Django 4.2.1 on 2023-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichimlik',
            name='rasm',
            field=models.ImageField(upload_to='ichimlik/'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='rasm',
            field=models.ImageField(upload_to='xodim/'),
        ),
        migrations.AlterField(
            model_name='yangilik',
            name='rasm',
            field=models.ImageField(upload_to='yangilik/'),
        ),
    ]
